[tool.poetry]
name = "ezbpg"
version = "0.1.2"
description = ""
authors = ["wstlabs <email-address-not-set@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]

